### ISSUE TITLE
Move modules to core.

### ISSUE THREAD

**Issue by Cajova-Houba** [Cajova-Houba/crce#4]
crce-webui and crce-concurency are to be moved to core.

crce-compatibility-api can be moved after default (empty) implementation is added (example in tests in compatibility-dao-mongodb).

crce-metadata-osgi-bundle can be moved after unit tests proving that this module is capable of indexing generic JARs (not just OSGIs) is made.

provision module should be moved somewhere outside of modules - most likely to build.

**Comment by Cajova-Houba** [comment]
This issue can be closed only after #5  and #6  are resolved.

**Comment by Cajova-Houba** [comment]
#8 needs to be resloved too before closing this issue.

**Comment by vairad** [comment]
crce-concurrency was moved

**Comment by vairad** [comment]
crce-compatibiliti-api was moved

**Comment by Cajova-Houba** [comment]
Modules moved and build is ok.
