### ISSUE TITLE
Move provision

### ISSUE THREAD

**Issue by Cajova-Houba** [Cajova-Houba/crce#7]
Move provision to separate folder in root dir (deploy, provision, something like that). Also create module in modules/ which will aggregate default modules to be included in vanilla installation.

**Comment by vairad** [comment]
Basic pom structres are created, but there is problem with startup of apache felix.
Bundles are prepared into run folder, but startup fails.

**Comment by vairad** [comment]
Task is done. CRCE starts correctly.
